name: revenue_performance
version: "1.0.0"
config-version: 2
profile: revenue_performance

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  revenue_performance:
    staging:
      +schema: staging
      +materialized: view
    intermediate:
      +schema: staging
      +materialized: view
    marts:
      +schema: analytics
      +materialized: table

seeds:
  revenue_performance:
    +schema: staging
